<a href="https://colab.research.google.com/github/naitikjpatel/naitikjpatel/blob/main/loadFile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Getting data from a text file

*Method 1:numpy.loadtxt()
*Method 2:numpy.genfromtxt()

(used when there are null value is the data and we want to handle them then use genfromtxt() method)

In [3]:
e0=np.loadtxt('ex_0.txt',dtype='int32')
e0

array([3, 4, 8, 9], dtype=int32)

In [5]:
e_0=np.genfromtxt('ex_0.txt',dtype="int")
e_0

array([3, 4, 8, 9])

In [9]:
e1=np.loadtxt('ex_1.txt',dtype="int32")
e1=np.genfromtxt('ex_1.txt',dtype="str")
e1

array([['1', '2'],
       ['3', '4'],
       ['5', '6'],
       ['7', '8'],
       ['9', '10']], dtype='<U2')

In [12]:
e2=np.loadtxt('ex_2.txt',dtype='str')
e2=np.genfromtxt('ex_2.txt',dtype='str')
e2



array([['1', 'Numpy'],
       ['2', 'Pandas'],
       ['3', 'matplotlib'],
       ['4', 'seaborn']], dtype='<U10')

*now here we see the some attribute or functionality of this two method

In [29]:
e3=np.loadtxt('ex_3.txt',dtype="str",skiprows=1)
e3=np.loadtxt('ex_3.txt',dtype="str",skiprows=2)
# e3=np.genfromtxt('ex_3.txt',dtype="str",skiprows=1) error

# genfromtxt()
e3=np.genfromtxt('ex_3.txt',dtype="str",skip_header=2)
e3=np.genfromtxt('ex_3.txt',dtype="str",skip_footer=2)
e3=np.genfromtxt('ex_3.txt',dtype="str",skip_header=1,skip_footer=1)

e3=np.loadtxt('ex_3.txt',usecols=2,dtype="str",skiprows=2)
e3=np.loadtxt('ex_3.txt',usecols=[1,2],dtype="str",skiprows=2)
e3

array([['Pandas', '28'],
       ['matplotlib', '22'],
       ['seaborn', '27'],
       ['Scipy', '25']], dtype='<U10')

*now we discuss about the delimeter

In [33]:
# e4=np.loadtxt('ex_4.txt',dtype="str",delimeter=",")
e4=np.genfromtxt("ex_4.txt",dtype="str",delimiter=",")
e4

array([['a', 'b', 'c', 'd'],
       ['e', 'f', 'g', 'h']], dtype='<U1')

In [42]:
e5=np.loadtxt('ex_5.txt',dtype='str',usecols=[1,2,3])
# e5=np.loadtxt('ex_5.txt',dtype="str",delimiter="\n") Error

e5=np.genfromtxt('ex_5.txt',dtype="str",delimiter="\n")
e5

array(['Welcome to the world of numpy!', 'It stands for Numerical Python',
       'Its backend is written in C language.',
       'Numpy is must for all Machine Learning aspirants.'], dtype='<U49')

In [47]:
# e6=np.loadtxt('ex_6.txt',dtype='str',delimiter=",") correct
# e6=np.loadtxt('ex_6.txt',dtype='int',delimiter=",")  error
'''
this is the exmple of the missing number/values
1,2,3,4
5,6,,8
'''


e6=np.genfromtxt('ex_6.txt',delimiter=",",missing_values=None,filling_values=0,dtype="int")
e6

array([[1, 2, 3, 4],
       [5, 6, 0, 8]])

# Case study - 1: Airbnb's nps

nps: Net Promoters' Score

Score   
1 to 6:    Detractors

7 or 8:    Neutral

9 or 10:   Promoters

nps = % of promters - % of detractors

**Example**

60% - Promoters

10% - Neutral

30% - Detractors

nps = 60 - 30 = 30

Therefore, usually nps above 70 is considered excellent.

In [48]:
air=np.loadtxt('airbnb_nps.txt',dtype='int')
air

array([ 7, 10,  5, ...,  5,  9, 10])

In [53]:
total=len(air)
print(total)

detractors=air[air<7] #detractors array ni list malshe
no_of_detractors=len(detractors)
# print(detractors)
# print(no_of_detractors)
pct_detractors=round(no_of_detractors*100/total,2)
print('pct_detractors =',pct_detractors)



no_of_neutrals=len(air[air<9])-no_of_detractors
pct_neutrals=round(no_of_neutrals*100/total,2)
print("pct_neutrals =",pct_neutrals)


no_of_promoters=len(air[air>=9])
pct_promoters=round(no_of_promoters*100/total,2)
print("pct_promoters =",pct_promoters)

nps=pct_promoters-pct_detractors
print("Nps :",nps)



1167
pct_detractors = 28.45
pct_neutrals = 19.37
pct_promoters = 52.19
Nps : 23.74


#Case Study2: Fibit's User's Analysis